server:
  port: 8085

spring:
  zipkin:
    enabled: false
  cloud:
    stream:
      defaultBinder: defaultRabbit
      bindings:
        outputProductAdd:
          destination: mqTestProduct
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
             rabbitmq:
              host: rabbit-server
              port: 5672
              username: test
              password: test
              virtual-host: /test
  application:
    name: spring-cloud-stream1