server:
  port: 8086

spring:
  zipkin:
    enabled: false
  cloud:
    stream:
      bindings:
        inputProductAdd:
          destination: mqTestProduct
          group: addProductHandler
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: rabbit-server #rabbitMQ服务器地址
                port: 5672          #rabbitMQ服务器端口
                username: test
                password: test
                virtual-host: /test