server:
  port: 8888

eureka:
  instance:
    appname: config
    metadata-map:
      cluster: moredo
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

spring:
  rabbitmq:
      host: rabbit-server
      port: 5672
      virtual-host: /test
      username: test
      password: test